"use strict";

const FAILURE_REASON_CODES = Object.freeze({
  LOGIN_CHECK_PASSED: "LOGIN_CHECK_PASSED",
  OTA_NOT_LOGGED_IN: "OTA_NOT_LOGGED_IN",
  LOGIN_CHECK_UNKNOWN: "LOGIN_CHECK_UNKNOWN",
  LOGIN_CHECK_ERROR: "LOGIN_CHECK_ERROR",
  INVALID_INPUT: "INVALID_INPUT",
  UNSUPPORTED_PLATFORM: "UNSUPPORTED_PLATFORM"
});

module.exports = {
  FAILURE_REASON_CODES
};
