"use strict";

const FAILURE_STAGE_BY_CODE = Object.freeze({
  INVALID_INPUT: "input_normalize",
  INVALID_SEGMENT: "input_normalize",
  EMPTY_SEGMENTS: "input_normalize",
  INVALID_DATE_RANGE: "input_normalize",
  EMPTY_ROOM_LIST: "input_normalize",
  INVALID_ROOM: "input_normalize",
  INVALID_ROOM_NAME: "input_normalize",
  INVALID_PRICE: "input_normalize",
  UNSUPPORTED_PLATFORM: "platform_routing",
  PLATFORM_NOT_IMPLEMENTED: "platform_capability_check",
  SEGMENT_SKIPPED_AFTER_FAILURE: "segment_orchestration",
  INPUT_RUNTIME_PATH_NOT_FOUND: "runtime_precheck",
  CDP_ENDPOINT_UNAVAILABLE: "runtime_precheck",
  CDP_CONNECT_FAILED: "runtime_precheck",
  CDP_NO_CONTEXT: "runtime_precheck",
  RUNTIME_CHROME_LAUNCH_FAILED: "runtime_precheck",
  PAGE_LOAD_TIMEOUT: "page_load",
  PAGE_NOT_READY: "page_load",
  TARGET_PAGE_LEFT: "page_guard",
  BROWSER_PROFILE_LOCKED: "runtime_precheck",
  NOT_LOGGED_IN: "precheck_login",
  LOGIN_EXPIRED: "precheck_login",
  OTA_LOGIN_REQUIRED: "precheck_login",
  ROOM_NOT_FOUND: "match_room",
  ROOM_NAME_AMBIGUOUS: "match_room",
  ROOM_SELECTION_NOT_CONFIRMED: "match_room",
  BOOKING_MULTI_SEGMENT_UNSUPPORTED: "platform_capability_check",
  BOOKING_MULTI_ROOM_UNSUPPORTED: "platform_capability_check",
  BULK_EDIT_NOT_FOUND: "open_bulk_edit",
  DATE_CELL_NOT_FOUND: "select_date_range",
  DATE_RANGE_NOT_MATCHED: "select_date_range",
  DATE_PANEL_STUCK: "select_date_range",
  PRICE_INPUT_NOT_FOUND: "fill_price",
  PRICE_INPUT_NOT_EDITABLE: "fill_price",
  PRICE_ECHO_NOT_MATCHED: "verify_price_echo",
  PRICE_ECHO_MISMATCH: "verify_price_echo",
  SUBMIT_BUTTON_NOT_FOUND: "submit",
  SUBMIT_DISABLED: "submit",
  SUBMIT_FAILED: "submit",
  BLOCKING_MODAL_FOUND: "submit",
  SUBMIT_CONFIRM_NOT_FOUND: "post_submit_verify",
  SUBMIT_CONFIRM_CLOSE_FAILED: "post_submit_verify",
  SUBMIT_RESULT_UNKNOWN: "post_submit_verify",
  PAGE_NOT_READY_AFTER_SUBMIT: "post_submit_verify",
  POST_SUBMIT_VERIFY_FAILED: "post_submit_verify",
  SCRIPT_EXCEPTION: "system",
  TIMEOUT: "system",
  UNKNOWN_ERROR: "system"
});

const DEFAULT_MESSAGE_BY_CODE = Object.freeze({
  INVALID_INPUT: "Invalid input.",
  INVALID_SEGMENT: "Invalid segment.",
  EMPTY_SEGMENTS: "segments must not be empty.",
  INVALID_DATE_RANGE: "Invalid date range.",
  EMPTY_ROOM_LIST: "roomList must not be empty.",
  INVALID_ROOM: "Invalid room item.",
  INVALID_ROOM_NAME: "roomName is required.",
  INVALID_PRICE: "price must be a positive numeric string.",
  UNSUPPORTED_PLATFORM: "Unsupported platform.",
  PLATFORM_NOT_IMPLEMENTED: "Platform is not implemented in V2 phase 1.",
  SEGMENT_SKIPPED_AFTER_FAILURE: "Segment skipped because an earlier segment failed.",
  INPUT_RUNTIME_PATH_NOT_FOUND: "Runtime path not found.",
  CDP_ENDPOINT_UNAVAILABLE: "CDP endpoint is unavailable.",
  CDP_CONNECT_FAILED: "CDP connection failed.",
  CDP_NO_CONTEXT: "CDP connection has no browser context.",
  RUNTIME_CHROME_LAUNCH_FAILED: "Chrome launch failed.",
  PAGE_LOAD_TIMEOUT: "Page load timed out.",
  PAGE_NOT_READY: "Page was not ready.",
  TARGET_PAGE_LEFT: "Page left the target price page.",
  BROWSER_PROFILE_LOCKED: "Browser profile is locked.",
  NOT_LOGGED_IN: "OTA backend is not logged in.",
  LOGIN_EXPIRED: "OTA login expired.",
  OTA_LOGIN_REQUIRED: "OTA login is required.",
  ROOM_NOT_FOUND: "Room not found.",
  ROOM_NAME_AMBIGUOUS: "Room name matched multiple candidates.",
  ROOM_SELECTION_NOT_CONFIRMED: "Selected room count did not match roomList.",
  BOOKING_MULTI_SEGMENT_UNSUPPORTED: "Booking V2 only supports one segment in this phase.",
  BOOKING_MULTI_ROOM_UNSUPPORTED: "Booking V2 only supports one room in this phase.",
  BULK_EDIT_NOT_FOUND: "Bulk edit button was not found.",
  DATE_CELL_NOT_FOUND: "Date cell not found.",
  DATE_RANGE_NOT_MATCHED: "Date range readback did not match.",
  DATE_PANEL_STUCK: "Date panel did not close.",
  PRICE_INPUT_NOT_FOUND: "Price input not found.",
  PRICE_INPUT_NOT_EDITABLE: "Price input is not editable.",
  PRICE_ECHO_NOT_MATCHED: "Price echo did not match.",
  PRICE_ECHO_MISMATCH: "Price echo did not match.",
  SUBMIT_BUTTON_NOT_FOUND: "Submit button not found.",
  SUBMIT_DISABLED: "Submit button is disabled.",
  SUBMIT_FAILED: "Submit failed.",
  BLOCKING_MODAL_FOUND: "Blocking modal found.",
  SUBMIT_CONFIRM_NOT_FOUND: "Submit success confirm button was not found.",
  SUBMIT_CONFIRM_CLOSE_FAILED: "Submit success dialog did not close.",
  SUBMIT_RESULT_UNKNOWN: "Submit result was unknown.",
  PAGE_NOT_READY_AFTER_SUBMIT: "Page was not ready after submit.",
  POST_SUBMIT_VERIFY_FAILED: "Post-submit verification failed.",
  SCRIPT_EXCEPTION: "Script exception.",
  TIMEOUT: "Execution timed out.",
  UNKNOWN_ERROR: "Unknown error."
});

module.exports = {
  FAILURE_STAGE_BY_CODE,
  DEFAULT_MESSAGE_BY_CODE
};
